version: "3.9"

services:
  server:
    container_name: "node-server"
    build: .    
    ports:
      - 5000:5000
  postgres:
    container_name: postgresdb
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "postgres"
      ## POSTGRES_DB: "postgres"
    ports:
      - 5555:5432 ## expose to different port to avoid conflict with host postgres
    restart: always